# Generated by Django 5.1.6 on 2025-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirtimePayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("service_provider", models.CharField(max_length=64)),
                ("fee", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "airtime_payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BankDeposits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "bank_deposits",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BundlesAndPacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("service_provider", models.CharField(max_length=64)),
                ("fee", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "bundles_and_packs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CashPowerPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("service_provider", models.CharField(max_length=64)),
                ("fee", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "cash_power_payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyRecieved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "money_recieved",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentToCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("code", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "payment_to_code",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransfersToMomo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("tel", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("fee", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "transfers_to_momo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Withdrawals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.CharField(max_length=64)),
                ("agent_tel", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("fee", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "withdrawals",
                "managed": False,
            },
        ),
    ]
